import 'dart:ui';

const API_LINK = "https://safsafdz.com";
const LOGIN_ENDPOINT = "$API_LINK/user-login";
const SIGNUP_ENDPOINT = "$API_LINK/user-registers";
const PRODUCT_ENDPOINT = "$API_LINK/products";
const IMAGES_ENDPOINT = "$API_LINK/";
const CATEGORIES_ENDPOINT = "$API_LINK/categories";
const SLIDERS_ENDPOINT = "$API_LINK/slides";
const SLIDERS_IMAGES_ENDPOINT = "$API_LINK/images/";
const TOKEN = "Bearer 78heoytx56drg4ezd16q3df782";
const UPDATE_PROFILE = "$API_LINK/user-update/";
const SUBMIT_ORDER = "$API_LINK/orders";
const PASSWORD_RESET = "$API_LINK/reset-passwordee";
const ORDERS_ENDPOINT = "$API_LINK/orders-user/";
const ORDERS_PDF = API_LINK;
const PHONE = "$API_LINK/phone-number";
const UPDATE = "$API_LINK/version-active";
const SEARCH = "$API_LINK/search";
const REMOVE_ACCOUNT = "$API_LINK/user-delete";
const MAIN_COLOR = Color(0xFF1dbac9);
const ORANGE_COLOR = Color(0xFFff9700);
const FORNISSEUR_ENDPOINT = "$API_LINK/grossists";
const GROSIST_SEARCH = "$API_LINK/grossist-search";
